// figma/src/app/components/image-occlusion-editor.tsx
import { useState, useRef, useEffect } from 'react';
import { Card } from '@/app/components/ui/card';
import { Button } from '@/app/components/ui/button';
import { Input } from '@/app/components/ui/input';
import { ImageOcclusion } from '@/types/flashcard';
import { X, Square, Pencil, Save, Trash2, Eye, EyeOff } from 'lucide-react';

interface ImageOcclusionEditorProps {
  imageUrl: string;
  occlusions?: ImageOcclusion[];
  onSave: (occlusions: ImageOcclusion[]) => void;
  onCancel: () => void;
}

export function ImageOcclusionEditor({
  imageUrl,
  occlusions = [],
  onSave,
  onCancel,
}: ImageOcclusionEditorProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [image, setImage] = useState<HTMLImageElement | null>(null);
  const [occlusionList, setOcclusionList] = useState<ImageOcclusion[]>(occlusions);
  const [isDrawing, setIsDrawing] = useState(false);
  const [currentPoints, setCurrentPoints] = useState<Array<{ x: number; y: number }>>([]);
  const [drawMode, setDrawMode] = useState<'rectangle' | 'polygon'>('rectangle');
  const [startPoint, setStartPoint] = useState<{ x: number; y: number } | null>(null);
  const [selectedOcclusion, setSelectedOcclusion] = useState<string | null>(null);
  const [hideOcclusions, setHideOcclusions] = useState(false);
  const [currentLabel, setCurrentLabel] = useState('');

  // Load image
  useEffect(() => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      setImage(img);
      drawCanvas(img, occlusionList);
    };
    img.src = imageUrl;
  }, [imageUrl]);

  // Redraw canvas when occlusions change
  useEffect(() => {
    if (image) {
      drawCanvas(image, occlusionList);
    }
  }, [occlusionList, image, hideOcclusions]);

  const drawCanvas = (img: HTMLImageElement, occlusions: ImageOcclusion[]) => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Set canvas size to match image
    const container = containerRef.current;
    if (container) {
      const maxWidth = container.clientWidth;
      const maxHeight = 600;
      const ratio = Math.min(maxWidth / img.width, maxHeight / img.height);
      
      canvas.width = img.width * ratio;
      canvas.height = img.height * ratio;
    }

    // Draw image
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

    // Draw occlusions
    if (!hideOcclusions) {
      occlusions.forEach((occlusion) => {
        drawOcclusion(ctx, occlusion, canvas.width / img.width, occlusion.id === selectedOcclusion);
      });
    }

    // Draw current drawing
    if (isDrawing && currentPoints.length > 0) {
      ctx.fillStyle = 'rgba(59, 130, 246, 0.5)';
      ctx.strokeStyle = '#3B82F6';
      ctx.lineWidth = 2;

      if (drawMode === 'rectangle' && startPoint && currentPoints.length > 0) {
        const current = currentPoints[currentPoints.length - 1];
        const width = current.x - startPoint.x;
        const height = current.y - startPoint.y;
        ctx.fillRect(startPoint.x, startPoint.y, width, height);
        ctx.strokeRect(startPoint.x, startPoint.y, width, height);
      } else if (drawMode === 'polygon') {
        ctx.beginPath();
        ctx.moveTo(currentPoints[0].x, currentPoints[0].y);
        currentPoints.forEach((point) => {
          ctx.lineTo(point.x, point.y);
        });
        ctx.closePath();
        ctx.fill();
        ctx.stroke();
      }
    }
  };

  const drawOcclusion = (
    ctx: CanvasRenderingContext2D,
    occlusion: ImageOcclusion,
    scale: number,
    isSelected: boolean
  ) => {
    const scaledPoints = occlusion.points.map(p => ({
      x: p.x * scale,
      y: p.y * scale,
    }));

    ctx.fillStyle = isSelected 
      ? 'rgba(245, 158, 11, 0.6)' 
      : 'rgba(59, 130, 246, 0.5)';
    ctx.strokeStyle = isSelected ? '#F59E0B' : '#3B82F6';
    ctx.lineWidth = isSelected ? 3 : 2;

    if (occlusion.type === 'rectangle' && scaledPoints.length === 2) {
      const width = scaledPoints[1].x - scaledPoints[0].x;
      const height = scaledPoints[1].y - scaledPoints[0].y;
      ctx.fillRect(scaledPoints[0].x, scaledPoints[0].y, width, height);
      ctx.strokeRect(scaledPoints[0].x, scaledPoints[0].y, width, height);
    } else if (occlusion.type === 'polygon') {
      ctx.beginPath();
      ctx.moveTo(scaledPoints[0].x, scaledPoints[0].y);
      scaledPoints.forEach((point) => {
        ctx.lineTo(point.x, point.y);
      });
      ctx.closePath();
      ctx.fill();
      ctx.stroke();
    }

    // Draw label
    if (occlusion.label && scaledPoints.length > 0) {
      ctx.fillStyle = isSelected ? '#F59E0B' : '#3B82F6';
      ctx.font = 'bold 14px sans-serif';
      ctx.fillText(occlusion.label, scaledPoints[0].x + 5, scaledPoints[0].y - 5);
    }
  };

  const handleCanvasClick = (e: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas || !image) return;

    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    if (drawMode === 'rectangle') {
      if (!isDrawing) {
        setIsDrawing(true);
        setStartPoint({ x, y });
        setCurrentPoints([{ x, y }]);
      } else {
        // Finish rectangle
        const scale = image.width / canvas.width;
        const points = [
          { x: startPoint!.x * scale, y: startPoint!.y * scale },
          { x: x * scale, y: y * scale },
        ];

        const newOcclusion: ImageOcclusion = {
          id: generateId(),
          type: 'rectangle',
          points,
          label: currentLabel || `Área ${occlusionList.length + 1}`,
        };

        setOcclusionList([...occlusionList, newOcclusion]);
        setIsDrawing(false);
        setStartPoint(null);
        setCurrentPoints([]);
        setCurrentLabel('');
      }
    } else if (drawMode === 'polygon') {
      if (!isDrawing) {
        setIsDrawing(true);
        setCurrentPoints([{ x, y }]);
      } else {
        setCurrentPoints([...currentPoints, { x, y }]);
      }
    }
  };

  const handleMouseMove = (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (!isDrawing || !image) return;

    const canvas = canvasRef.current;
    if (!canvas) return;

    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    if (drawMode === 'rectangle' && startPoint) {
      setCurrentPoints([{ x, y }]);
      drawCanvas(image, occlusionList);
    }
  };

  const finishPolygon = () => {
    if (!isDrawing || currentPoints.length < 3 || !image) return;

    const canvas = canvasRef.current;
    if (!canvas) return;

    const scale = image.width / canvas.width;
    const points = currentPoints.map(p => ({
      x: p.x * scale,
      y: p.y * scale,
    }));

    const newOcclusion: ImageOcclusion = {
      id: generateId(),
      type: 'polygon',
      points,
      label: currentLabel || `Área ${occlusionList.length + 1}`,
    };

    setOcclusionList([...occlusionList, newOcclusion]);
    setIsDrawing(false);
    setCurrentPoints([]);
    setCurrentLabel('');
  };

  const deleteOcclusion = (id: string) => {
    setOcclusionList(occlusionList.filter(o => o.id !== id));
    setSelectedOcclusion(null);
  };

  const handleSave = () => {
    onSave(occlusionList);
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] dark:bg-[#0F172A] p-4">
      <div className="max-w-6xl mx-auto">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">
              Editor de Oclusão de Imagem
            </h1>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Desenhe retângulos ou polígonos para criar máscaras
            </p>
          </div>
          <Button variant="ghost" onClick={onCancel}>
            <X className="w-5 h-5" />
          </Button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Canvas Area */}
          <div className="lg:col-span-3">
            <Card className="p-4 bg-white dark:bg-gray-800 border-0 shadow-lg">
              <div className="mb-4 flex gap-2">
                <Button
                  variant={drawMode === 'rectangle' ? 'default' : 'outline'}
                  onClick={() => setDrawMode('rectangle')}
                  className={drawMode === 'rectangle' ? 'bg-[#3B82F6]' : ''}
                >
                  <Square className="w-4 h-4 mr-2" />
                  Retângulo
                </Button>
                <Button
                  variant={drawMode === 'polygon' ? 'default' : 'outline'}
                  onClick={() => setDrawMode('polygon')}
                  className={drawMode === 'polygon' ? 'bg-[#3B82F6]' : ''}
                >
                  <Pencil className="w-4 h-4 mr-2" />
                  Polígono
                </Button>
                {drawMode === 'polygon' && isDrawing && (
                  <Button
                    onClick={finishPolygon}
                    disabled={currentPoints.length < 3}
                    className="bg-[#10B981] hover:bg-[#059669] text-white"
                  >
                    Finalizar Polígono
                  </Button>
                )}
                <Button
                  variant="outline"
                  onClick={() => setHideOcclusions(!hideOcclusions)}
                >
                  {hideOcclusions ? (
                    <><Eye className="w-4 h-4 mr-2" /> Mostrar</>
                  ) : (
                    <><EyeOff className="w-4 h-4 mr-2" /> Ocultar</>
                  )}
                </Button>
              </div>

              {isDrawing && (
                <div className="mb-4">
                  <Input
                    value={currentLabel}
                    onChange={(e) => setCurrentLabel(e.target.value)}
                    placeholder="Nome da área (opcional)"
                    className="max-w-xs"
                  />
                </div>
              )}

              <div ref={containerRef} className="bg-gray-100 dark:bg-gray-900 rounded-lg overflow-hidden">
                <canvas
                  ref={canvasRef}
                  onClick={handleCanvasClick}
                  onMouseMove={handleMouseMove}
                  className="w-full cursor-crosshair"
                />
              </div>

              <p className="text-xs text-gray-500 dark:text-gray-400 mt-4">
                {drawMode === 'rectangle' 
                  ? 'Clique para começar e clique novamente para finalizar o retângulo'
                  : 'Clique para adicionar pontos ao polígono. Clique em "Finalizar Polígono" quando terminar'
                }
              </p>
            </Card>
          </div>

          {/* Occlusion List */}
          <div className="lg:col-span-1">
            <Card className="p-4 bg-white dark:bg-gray-800 border-0 shadow-lg">
              <h3 className="font-semibold text-gray-900 dark:text-white mb-4">
                Máscaras ({occlusionList.length})
              </h3>

              <div className="space-y-2 mb-4">
                {occlusionList.map((occlusion) => (
                  <div
                    key={occlusion.id}
                    className={`p-3 rounded-lg border-2 cursor-pointer transition-colors ${
                      selectedOcclusion === occlusion.id
                        ? 'border-[#F59E0B] bg-[#F59E0B]/10'
                        : 'border-gray-200 dark:border-gray-700 hover:border-[#3B82F6]'
                    }`}
                    onClick={() => setSelectedOcclusion(occlusion.id)}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-gray-900 dark:text-white truncate">
                          {occlusion.label}
                        </p>
                        <p className="text-xs text-gray-500 dark:text-gray-400 capitalize">
                          {occlusion.type}
                        </p>
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          deleteOcclusion(occlusion.id);
                        }}
                      >
                        <Trash2 className="w-4 h-4 text-red-500" />
                      </Button>
                    </div>
                  </div>
                ))}

                {occlusionList.length === 0 && (
                  <div className="text-center py-8 text-gray-400">
                    <p className="text-sm">Nenhuma máscara criada</p>
                  </div>
                )}
              </div>

              <div className="space-y-2">
                <Button
                  onClick={handleSave}
                  disabled={occlusionList.length === 0}
                  className="w-full bg-[#10B981] hover:bg-[#059669] text-white"
                >
                  <Save className="w-4 h-4 mr-2" />
                  Salvar ({occlusionList.length})
                </Button>
                <Button
                  onClick={onCancel}
                  variant="outline"
                  className="w-full"
                >
                  Cancelar
                </Button>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}

function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

// src/components/ImageOcclusionEditor.vue
<script setup lang="ts">
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import type { ImageOcclusion } from '@/types/flashcard'
import { Check, RotateCcw, Square, Trash2, Upload } from 'lucide-vue-next'
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'

interface Props {
  imageData?: string
  occlusions?: ImageOcclusion[]
}

const props = defineProps<Props>()

const emit = defineEmits<{
  'update:imageData': [value: string]
  'update:occlusions': [value: ImageOcclusion[]]
  save: [data: { imageData: string; occlusions: ImageOcclusion[] }]
  cancel: []
}>()

const canvasRef = ref<HTMLCanvasElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
const fileInputRef = ref<HTMLInputElement | null>(null)

const imageData = ref(props.imageData || '')
const occlusions = ref<ImageOcclusion[]>(props.occlusions || [])
const isDrawing = ref(false)
const startPoint = ref<{ x: number; y: number } | null>(null)
const currentRect = ref<{ x: number; y: number; width: number; height: number } | null>(null)
const selectedOcclusionId = ref<string | null>(null)
const imageElement = ref<HTMLImageElement | null>(null)
const canvasScale = ref(1)
const imageLoaded = ref(false)

const hasImage = computed(() => !!imageData.value)
const canSave = computed(() => hasImage.value && occlusions.value.length > 0)

function generateId(): string {
  return `occ-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
}

function clearImage() {
  imageData.value = ''
  occlusions.value = []
  imageElement.value = null
  imageLoaded.value = false
  selectedOcclusionId.value = null
  emit('update:imageData', '')
  emit('update:occlusions', [])
  // Reset file input
  if (fileInputRef.value) {
    fileInputRef.value.value = ''
  }
}

function handleFileSelect(event: Event) {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return

  imageLoaded.value = false
  
  const reader = new FileReader()
  reader.onload = (e) => {
    imageData.value = e.target?.result as string
    emit('update:imageData', imageData.value)
    nextTick(() => {
      loadImageAndSetupCanvas()
    })
  }
  reader.readAsDataURL(file)
}

function triggerFileInput() {
  fileInputRef.value?.click()
}

function loadImageAndSetupCanvas() {
  if (!imageData.value) return
  
  const img = new Image()
  img.crossOrigin = 'anonymous'
  
  img.onload = () => {
    imageElement.value = img
    imageLoaded.value = true
    nextTick(() => {
      setupCanvas()
    })
  }
  
  img.onerror = () => {
    console.error('Failed to load image')
    imageLoaded.value = false
  }
  
  img.src = imageData.value
}

function setupCanvas() {
  const canvas = canvasRef.value
  const container = containerRef.value
  const img = imageElement.value

  if (!canvas || !container || !img) {
    console.warn('Canvas setup failed - missing elements', { canvas: !!canvas, container: !!container, img: !!img })
    return
  }

  // Get container width (use a minimum to prevent issues)
  const containerWidth = Math.max(container.clientWidth, 200)
  // For mobile, use a smaller max height
  const isMobile = window.innerWidth < 640
  const maxHeight = isMobile ? 280 : 400

  // Calculate scale to fit container while maintaining aspect ratio
  const scaleX = containerWidth / img.width
  const scaleY = maxHeight / img.height
  const displayScale = Math.min(scaleX, scaleY, 1)
  canvasScale.value = displayScale

  // Calculate display dimensions
  const displayWidth = Math.floor(img.width * displayScale)
  const displayHeight = Math.floor(img.height * displayScale)
  
  // Get device pixel ratio for high DPI displays
  const dpr = window.devicePixelRatio || 1
  
  // Set canvas internal dimensions for high quality rendering
  // Canvas draws at full resolution (or scaled by DPR for retina)
  canvas.width = img.width * Math.min(dpr, 2) // Limit to 2x for performance
  canvas.height = img.height * Math.min(dpr, 2)
  
  // Set CSS dimensions for display
  canvas.style.width = `${displayWidth}px`
  canvas.style.height = `${displayHeight}px`

  redrawCanvas()
}

function redrawCanvas() {
  const canvas = canvasRef.value
  const ctx = canvas?.getContext('2d')
  const img = imageElement.value

  if (!canvas || !ctx || !img) return

  // Get device pixel ratio
  const dpr = Math.min(window.devicePixelRatio || 1, 2)
  
  // Scale factor from original image to canvas internal dimensions
  const internalScale = canvas.width / img.width

  // Clear canvas
  ctx.clearRect(0, 0, canvas.width, canvas.height)

  // Enable image smoothing for better quality
  ctx.imageSmoothingEnabled = true
  ctx.imageSmoothingQuality = 'high'

  // Draw image at full canvas resolution
  ctx.drawImage(img, 0, 0, canvas.width, canvas.height)

  // Draw existing occlusions (using internal scale, not display scale)
  occlusions.value.forEach((occ, index) => {
    const x = occ.x * internalScale
    const y = occ.y * internalScale
    const width = occ.width * internalScale
    const height = occ.height * internalScale

    // Draw filled rectangle
    ctx.fillStyle = selectedOcclusionId.value === occ.id
      ? 'rgba(59, 130, 246, 0.7)'
      : 'rgba(239, 68, 68, 0.6)'
    ctx.fillRect(x, y, width, height)

    // Draw border
    ctx.strokeStyle = selectedOcclusionId.value === occ.id
      ? 'rgba(59, 130, 246, 1)'
      : 'rgba(239, 68, 68, 1)'
    ctx.lineWidth = 2 * dpr
    ctx.strokeRect(x, y, width, height)

    // Draw label number
    ctx.fillStyle = 'white'
    const fontSize = Math.max(14 * dpr, Math.min(width, height) * 0.35)
    ctx.font = `bold ${fontSize}px sans-serif`
    ctx.textAlign = 'center'
    ctx.textBaseline = 'middle'
    ctx.fillText(`${index + 1}`, x + width / 2, y + height / 2)
  })

  // Draw current drawing rectangle
  if (currentRect.value) {
    const x = currentRect.value.x * internalScale
    const y = currentRect.value.y * internalScale
    const width = currentRect.value.width * internalScale
    const height = currentRect.value.height * internalScale
    
    ctx.fillStyle = 'rgba(59, 130, 246, 0.3)'
    ctx.fillRect(x, y, width, height)
    ctx.strokeStyle = 'rgba(59, 130, 246, 1)'
    ctx.lineWidth = 2 * dpr
    ctx.setLineDash([5 * dpr, 5 * dpr])
    ctx.strokeRect(x, y, width, height)
    ctx.setLineDash([])
  }
}

function getCanvasCoordinates(event: MouseEvent | TouchEvent): { x: number; y: number } {
  const canvas = canvasRef.value
  if (!canvas) return { x: 0, y: 0 }

  const rect = canvas.getBoundingClientRect()
  let clientX: number
  let clientY: number

  if ('touches' in event && event.touches.length > 0) {
    clientX = event.touches[0]!.clientX
    clientY = event.touches[0]!.clientY
  } else if ('changedTouches' in event && event.changedTouches.length > 0) {
    clientX = event.changedTouches[0]!.clientX
    clientY = event.changedTouches[0]!.clientY
  } else if ('clientX' in event) {
    clientX = event.clientX
    clientY = event.clientY
  } else {
    return { x: 0, y: 0 }
  }

  // Get coordinates relative to canvas, then convert to original image coordinates
  const x = (clientX - rect.left) / canvasScale.value
  const y = (clientY - rect.top) / canvasScale.value

  return { x, y }
}

function handleTouchStart(event: TouchEvent) {
  event.preventDefault()
  event.stopPropagation()
  handleMouseDown(event)
}

function handleTouchMove(event: TouchEvent) {
  event.preventDefault()
  event.stopPropagation()
  handleMouseMove(event)
}

function handleTouchEnd(event: TouchEvent) {
  event.preventDefault()
  event.stopPropagation()
  handleMouseUp(event)
}

function handleMouseDown(event: MouseEvent | TouchEvent) {
  if (!hasImage.value || !imageLoaded.value) return

  const coords = getCanvasCoordinates(event)

  // Check if clicking on existing occlusion
  const clickedOcclusion = occlusions.value.find(occ =>
    coords.x >= occ.x &&
    coords.x <= occ.x + occ.width &&
    coords.y >= occ.y &&
    coords.y <= occ.y + occ.height
  )

  if (clickedOcclusion) {
    selectedOcclusionId.value = clickedOcclusion.id
    redrawCanvas()
    return
  }

  // Start drawing new rectangle
  selectedOcclusionId.value = null
  isDrawing.value = true
  startPoint.value = coords
  currentRect.value = { x: coords.x, y: coords.y, width: 0, height: 0 }
}

function handleMouseMove(event: MouseEvent | TouchEvent) {
  if (!isDrawing.value || !startPoint.value) return

  const coords = getCanvasCoordinates(event)

  // Calculate rectangle (handle negative dimensions)
  const x = Math.min(startPoint.value.x, coords.x)
  const y = Math.min(startPoint.value.y, coords.y)
  const width = Math.abs(coords.x - startPoint.value.x)
  const height = Math.abs(coords.y - startPoint.value.y)

  currentRect.value = { x, y, width, height }
  redrawCanvas()
}

function handleMouseUp(event: MouseEvent | TouchEvent) {
  if (!isDrawing.value || !currentRect.value) {
    isDrawing.value = false
    return
  }

  // Only add if rectangle has meaningful size (smaller threshold for mobile)
  const minSize = window.innerWidth < 640 ? 5 : 10
  if (currentRect.value.width > minSize && currentRect.value.height > minSize) {
    const newOcclusion: ImageOcclusion = {
      id: generateId(),
      x: currentRect.value.x,
      y: currentRect.value.y,
      width: currentRect.value.width,
      height: currentRect.value.height,
    }
    occlusions.value.push(newOcclusion)
    emit('update:occlusions', occlusions.value)
  }

  isDrawing.value = false
  startPoint.value = null
  currentRect.value = null
  redrawCanvas()
}

function deleteSelectedOcclusion() {
  if (!selectedOcclusionId.value) return

  occlusions.value = occlusions.value.filter(occ => occ.id !== selectedOcclusionId.value)
  selectedOcclusionId.value = null
  emit('update:occlusions', occlusions.value)
  redrawCanvas()
}

function clearAllOcclusions() {
  occlusions.value = []
  selectedOcclusionId.value = null
  emit('update:occlusions', occlusions.value)
  redrawCanvas()
}

function handleSave() {
  emit('save', {
    imageData: imageData.value,
    occlusions: occlusions.value,
  })
}

function handleResize() {
  if (imageLoaded.value) {
    setupCanvas()
  }
}

// Watch for prop changes
watch(() => props.imageData, (newVal) => {
  if (newVal !== imageData.value) {
    imageData.value = newVal || ''
    if (imageData.value) {
      nextTick(() => loadImageAndSetupCanvas())
    }
  }
})

watch(() => props.occlusions, (newVal) => {
  if (newVal) {
    occlusions.value = [...newVal]
    redrawCanvas()
  }
}, { deep: true })

onMounted(() => {
  if (imageData.value) {
    loadImageAndSetupCanvas()
  }
  window.addEventListener('resize', handleResize)
})

onUnmounted(() => {
  window.removeEventListener('resize', handleResize)
})
</script>

<template>
  <div class="space-y-3">
    <!-- Hidden file input -->
    <input
      ref="fileInputRef"
      type="file"
      accept="image/*"
      class="hidden"
      @change="handleFileSelect"
    />

    <!-- Image Upload Area -->
    <div v-if="!hasImage" class="space-y-3">
      <Card
        class="p-6 sm:p-8 border-2 border-dashed border-border cursor-pointer hover:border-primary hover:bg-muted/50 transition-colors"
        @click="triggerFileInput"
      >
        <div class="text-center">
          <Upload class="w-10 h-10 sm:w-12 sm:h-12 mx-auto text-muted-foreground mb-2" />
          <p class="text-foreground font-medium mb-1 text-sm sm:text-base">
            Toque para enviar uma imagem
          </p>
          <p class="text-xs sm:text-sm text-muted-foreground">
            PNG, JPG ou GIF
          </p>
        </div>
      </Card>
    </div>

    <!-- Canvas Editor -->
    <div v-else class="space-y-3">
      <!-- Toolbar - simplified for mobile -->
      <div class="flex items-center gap-2 flex-wrap">
        <Button variant="outline" size="sm" @click="triggerFileInput" class="text-xs sm:text-sm">
          <Upload class="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
          <span class="hidden xs:inline">Nova </span>Imagem
        </Button>
        <Button
          variant="outline"
          size="sm"
          class="text-xs sm:text-sm"
          @click="clearImage"
        >
          <X class="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
          Remover
        </Button>
        <Button
          v-if="occlusions.length > 0"
          variant="outline"
          size="sm"
          class="text-xs sm:text-sm"
          @click="clearAllOcclusions"
        >
          <RotateCcw class="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
          Limpar
        </Button>
        <Button
          v-if="selectedOcclusionId"
          variant="destructive"
          size="sm"
          class="text-xs sm:text-sm ml-auto"
          @click="deleteSelectedOcclusion"
        >
          <Trash2 class="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
          Excluir
        </Button>
      </div>

      <!-- Instructions - compact for mobile -->
      <div class="bg-muted/50 rounded-lg p-2 sm:p-3">
        <div class="flex items-start gap-2">
          <Square class="w-3 h-3 sm:w-4 sm:h-4 text-primary mt-0.5 flex-shrink-0" />
          <div class="text-xs sm:text-sm text-muted-foreground">
            <p class="font-medium text-foreground">Desenhe as áreas de oclusão</p>
            <p class="hidden sm:block">Clique e arraste para criar retângulos nas áreas que devem ficar ocultas.</p>
            <p class="sm:hidden">Toque e arraste para criar os retângulos.</p>
          </div>
        </div>
      </div>

      <!-- Canvas Container - fixed sizing -->
      <div
        ref="containerRef"
        class="relative bg-muted rounded-lg overflow-hidden border border-border flex items-center justify-center"
        style="min-height: 150px;"
      >
        <!-- Loading state -->
        <div v-if="hasImage && !imageLoaded" class="absolute inset-0 flex items-center justify-center">
          <div class="text-muted-foreground text-sm">Carregando imagem...</div>
        </div>
        
        <!-- Canvas -->
        <canvas
          v-show="imageLoaded"
          ref="canvasRef"
          class="block touch-none cursor-crosshair max-w-full"
          @mousedown="handleMouseDown"
          @mousemove="handleMouseMove"
          @mouseup="handleMouseUp"
          @mouseleave="handleMouseUp"
          @touchstart.passive="handleTouchStart"
          @touchmove.passive="handleTouchMove"
          @touchend.passive="handleTouchEnd"
        />
      </div>

      <!-- Occlusion List - compact chips -->
      <div v-if="occlusions.length > 0" class="space-y-1">
        <p class="text-xs font-medium text-muted-foreground">
          {{ occlusions.length }} área(s) de oclusão
        </p>
        <div class="flex flex-wrap gap-1.5">
          <button
            v-for="(occ, index) in occlusions"
            :key="occ.id"
            :class="[
              'px-2.5 py-1 rounded-full text-xs font-medium transition-colors',
              selectedOcclusionId === occ.id
                ? 'bg-primary text-primary-foreground'
                : 'bg-muted text-muted-foreground hover:bg-muted/80',
            ]"
            @click="selectedOcclusionId = occ.id; redrawCanvas()"
          >
            {{ index + 1 }}
          </button>
        </div>
      </div>

      <!-- Action Buttons - stack on mobile -->
      <div class="flex flex-col sm:flex-row gap-2 pt-1">
        <Button
          :disabled="!canSave"
          class="flex-1 text-sm"
          @click="handleSave"
        >
          <Check class="w-4 h-4 mr-1.5" />
          Criar com {{ occlusions.length }} Oclusão
        </Button>
        <Button variant="outline" class="text-sm" @click="emit('cancel')">
          Cancelar
        </Button>
      </div>
    </div>
  </div>
</template>
