// src/components/BottomNav.vue
<script setup lang="ts">
import { BarChart3, FolderOpen, Home, Settings } from 'lucide-vue-next';

interface Props {
  currentView: string
}

defineProps<Props>()

const emit = defineEmits<{
  navigate: [view: string]
}>()

const navItems = [
  { id: 'home', icon: Home, label: 'Início' },
  { id: 'decks', icon: FolderOpen, label: 'Baralhos' },
  { id: 'stats', icon: BarChart3, label: 'Estatísticas' },
  { id: 'settings', icon: Settings, label: 'Ajustes' },
]
</script>

<template>
  <div class="fixed bottom-0 left-0 right-0 bg-card border-t border-border safe-area-inset-bottom z-50">
    <div class="max-w-2xl mx-auto">
      <div class="grid grid-cols-4 gap-1 p-2">
        <button
          v-for="item in navItems"
          :key="item.id"
          :class="[
            'flex flex-col items-center justify-center py-2 px-3 rounded-lg transition-colors',
            currentView === item.id
              ? 'bg-primary text-primary-foreground'
              : 'text-muted-foreground hover:bg-accent',
          ]"
          @click="emit('navigate', item.id)"
        >
          <component :is="item.icon" class="w-5 h-5 mb-1" />
          <span class="text-xs font-medium">{{ item.label }}</span>
        </button>
      </div>
    </div>
  </div>
</template>

// figma/src/app/components/bottom-nav.tsx
import { Home, FolderOpen, Settings, BarChart3 } from 'lucide-react';

interface BottomNavProps {
  currentView: string;
  onNavigate: (view: string) => void;
}

export function BottomNav({ currentView, onNavigate }: BottomNavProps) {
  const navItems = [
    { id: 'home', icon: Home, label: 'Início' },
    { id: 'decks', icon: FolderOpen, label: 'Baralhos' },
    { id: 'stats', icon: BarChart3, label: 'Estatísticas' },
    { id: 'settings', icon: Settings, label: 'Ajustes' },
  ];

  return (
    <div className="fixed bottom-0 left-0 right-0 bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 safe-area-inset-bottom z-50">
      <div className="max-w-2xl mx-auto">
        <div className="grid grid-cols-4 gap-1 p-2">
          {navItems.map((item) => {
            const Icon = item.icon;
            const isActive = currentView === item.id;

            return (
              <button
                key={item.id}
                onClick={() => onNavigate(item.id)}
                className={`flex flex-col items-center justify-center py-2 px-3 rounded-lg transition-colors ${
                  isActive
                    ? 'bg-[#3B82F6] text-white'
                    : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700'
                }`}
              >
                <Icon className="w-5 h-5 mb-1" />
                <span className="text-xs font-medium">{item.label}</span>
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
}
