// src/components/CardRenderer.vue
<script setup lang="ts">
import type { Card } from '@/types/flashcard'
import hljs from 'highlight.js'
import 'highlight.js/styles/atom-one-dark.css'
import katex from 'katex'
import 'katex/dist/katex.min.css'
import MarkdownIt from 'markdown-it'
import { computed } from 'vue'
import OcclusionCardViewer from './OcclusionCardViewer.vue'

interface Props {
  card: Card
  showAnswer: boolean
}

const props = defineProps<Props>()

const md = new MarkdownIt({
  html: false,
  linkify: true,
  typographer: true,
  highlight: (str: string, lang: string) => {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(str, { language: lang }).value
      } catch (_) {}
    }
    return ''
  },
})

const isOcclusion = computed(() => props.card.content.type === 'occlusion')

const renderedFront = computed(() => {
  if (props.card.content.type === 'text') {
    return md.render(props.card.content.front)
  }
  return props.card.content.front
})

const renderedBack = computed(() => {
  const content = props.card.content
  
  switch (content.type) {
    case 'text':
      return md.render(content.back)
    
    case 'code':
      const lang = content.language || 'javascript'
      try {
        const highlighted = hljs.highlight(content.back, { language: lang }).value
        return `<pre class="hljs rounded-lg p-4 overflow-x-auto"><code>${highlighted}</code></pre>`
      } catch (_) {
        return `<pre class="bg-muted rounded-lg p-4 overflow-x-auto"><code>${content.back}</code></pre>`
      }
    
    case 'latex':
      try {
        return `<div class="flex items-center justify-center p-4 bg-card rounded-lg">${katex.renderToString(content.back, { displayMode: true })}</div>`
      } catch (error) {
        return `<div class="bg-destructive/10 border border-destructive/30 rounded-lg p-4">
          <p class="text-destructive text-sm">Erro ao renderizar LaTeX</p>
          <pre class="mt-2 text-xs font-mono text-muted-foreground">${content.back}</pre>
        </div>`
      }
    
    case 'image':
      return content.back
    
    case 'occlusion':
      return '' // Handled separately
    
    default:
      return content.back
  }
})
</script>

<template>
  <div class="space-y-6">
    <!-- Occlusion Card Type -->
    <template v-if="isOcclusion">
      <div>
        <div class="text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide">
          Imagem com Oclusão
        </div>
        <div class="bg-muted/30 rounded-lg p-4">
          <OcclusionCardViewer
            v-if="card.content.imageData && card.content.imageOcclusions"
            :image-data="card.content.imageData"
            :occlusions="card.content.imageOcclusions"
            :interactive="true"
          />
        </div>
        <p class="text-xs text-muted-foreground mt-2 text-center">
          Clique nas áreas vermelhas para revelar o conteúdo
        </p>
      </div>
    </template>

    <!-- Regular Card Types -->
    <template v-else>
      <!-- Front (Question) -->
      <div>
        <div class="text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide">
          Pergunta
        </div>
        <div class="bg-muted/50 rounded-lg p-4">
          <div v-if="card.content.type === 'text'" class="prose dark:prose-invert" v-html="renderedFront" />
          <p v-else class="text-foreground">{{ card.content.front }}</p>
        </div>
      </div>

      <!-- Back (Answer) -->
      <div v-if="showAnswer">
        <div class="text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide">
          Resposta
        </div>
        <div class="bg-muted/50 rounded-lg p-4">
          <!-- Image type -->
          <template v-if="card.content.type === 'image'">
            <div class="space-y-3">
              <div v-if="card.content.imageUrl" class="rounded-lg overflow-hidden border border-border">
                <img
                  :src="card.content.imageUrl"
                  alt="Card content"
                  class="w-full max-h-96 object-contain bg-muted"
                />
              </div>
              <p class="text-foreground">{{ card.content.back }}</p>
            </div>
          </template>
          
          <!-- Other types with HTML rendering -->
          <template v-else>
            <div class="prose dark:prose-invert max-w-none" v-html="renderedBack" />
          </template>
        </div>
      </div>
    </template>
  </div>
</template>

<style>
/* Highlight.js theme integration */
.hljs {
  background: #282c34 !important;
  color: #abb2bf;
}
</style>

// figma/src/app/components/card-renderer.tsx
import { Card as FlashCard } from '@/types/flashcard';
import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import 'katex/dist/katex.min.css';
import { InlineMath, BlockMath } from 'react-katex';

interface CardRendererProps {
  card: FlashCard;
  showAnswer: boolean;
}

export function CardRenderer({ card, showAnswer }: CardRendererProps) {
  const renderContent = (content: string, type: string, isAnswer: boolean) => {
    switch (type) {
      case 'text':
        return (
          <div className="prose dark:prose-invert max-w-none">
            <ReactMarkdown
              components={{
                code({ node, inline, className, children, ...props }: any) {
                  return inline ? (
                    <code className="bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded text-sm font-mono" {...props}>
                      {children}
                    </code>
                  ) : (
                    <code className="block bg-gray-100 dark:bg-gray-800 p-2 rounded text-sm font-mono" {...props}>
                      {children}
                    </code>
                  );
                },
              }}
            >
              {content}
            </ReactMarkdown>
          </div>
        );

      case 'code':
        if (isAnswer) {
          return (
            <SyntaxHighlighter
              language={card.content.language || 'javascript'}
              style={oneDark}
              customStyle={{
                borderRadius: '0.5rem',
                fontSize: '0.875rem',
                margin: 0,
              }}
            >
              {content}
            </SyntaxHighlighter>
          );
        }
        return <p className="text-gray-900 dark:text-white">{content}</p>;

      case 'latex':
        if (isAnswer) {
          try {
            // Try to render as block math
            return (
              <div className="flex items-center justify-center p-4 bg-white dark:bg-gray-900 rounded-lg">
                <BlockMath math={content} />
              </div>
            );
          } catch (error) {
            return (
              <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
                <p className="text-red-600 dark:text-red-400 text-sm">
                  Erro ao renderizar LaTeX: {(error as Error).message}
                </p>
                <pre className="mt-2 text-xs font-mono text-gray-600 dark:text-gray-400">
                  {content}
                </pre>
              </div>
            );
          }
        }
        return <p className="text-gray-900 dark:text-white">{content}</p>;

      case 'image':
        if (isAnswer) {
          return (
            <div className="space-y-3">
              {card.content.imageUrl && (
                <div className="rounded-lg overflow-hidden border border-gray-200 dark:border-gray-700">
                  <img
                    src={card.content.imageUrl}
                    alt="Card content"
                    className="w-full max-h-96 object-contain bg-gray-50 dark:bg-gray-900"
                    onError={(e) => {
                      e.currentTarget.src = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="300" height="200"%3E%3Crect fill="%23ddd" width="300" height="200"/%3E%3Ctext fill="%23999" x="50%25" y="50%25" text-anchor="middle" dy=".3em"%3EImagem não encontrada%3C/text%3E%3C/svg%3E';
                    }}
                  />
                </div>
              )}
              <p className="text-gray-900 dark:text-white">{content}</p>
            </div>
          );
        }
        return <p className="text-gray-900 dark:text-white">{content}</p>;

      default:
        return <p className="text-gray-900 dark:text-white">{content}</p>;
    }
  };

  return (
    <div className="space-y-6">
      {/* Front (Question) */}
      <div>
        <div className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-2 uppercase tracking-wide">
          Pergunta
        </div>
        <div className="bg-gray-50 dark:bg-gray-900/50 rounded-lg p-4">
          {renderContent(card.content.front, card.content.type, false)}
        </div>
      </div>

      {/* Back (Answer) */}
      {showAnswer && (
        <div>
          <div className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-2 uppercase tracking-wide">
            Resposta
          </div>
          <div className="bg-gray-50 dark:bg-gray-900/50 rounded-lg p-4">
            {renderContent(card.content.back, card.content.type, true)}
          </div>
        </div>
      )}
    </div>
  );
}
